server:
   connection-timeout: 10000
   port: 8088 #配置端口号

spring:
   devtools:
      restart:
         enabled: true  #设置开启热部署
   freemarker:
      cache: false    #页面不加载缓存，修改即时生效
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/syy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root #数据库用户名
      password: ssss1111 #数据库密码
      driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动
      initialSize: 10 #初始化连接池大小
      minIdle: 10 #初始化最小连接池数量
      maxActive: 100 #初始化最大连接池数量
      maxWait: 6000 #配置获取连接等待超时的时间
      timeBetweenEvictionRunsMills: 6000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 30000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL #测试连接
mybatis:
   type-aliases-package: com.yang.model
   mapper-locations: classpath:/mapper/*.xml
   configuration:
      map-underscore-to-camel-case: true
      #打印sql
      #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper:
   mappers: com.yang.base.TkMapper  #扫描基类接口
   identity: mysql

logging:
   level:
      root: debug

apollo:
   bootstrap:
      enabled: true
      namespaces: application,yang,test.yml

